server:
  port: 8030

spring:
  application:
    name: client-8030
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /user
    template:
      retry:
        enabled: true
      listener:
        simple:
          acknowledge-mode: manual
      type: simple
      publisher-returns: true
      publisher-confirm-type: correlated

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false


